openapi: 3.0.0
tags:
  - name: admin
  - name: user
info:
  title: resthub
  version: '1.0'
  contact:
    email: osamu.mitsuhashi224@gmail.com
  description: RestHub api document
servers:
  - url: 'http://localhost:3000'
paths:
  /users:
    post:
      summary: Create New User
      operationId: post-user
      tags:
        - user
      responses:
        '201':
          description: User Created
      description: ユーザー作成
